### ISSUE TITLE
Sunday to-do List

### ISSUE THREAD

**Issue by matthewrw** [matthewrw/LM_Project#3]
What do we have left to do and want to accomplish on Sunday? Probably everything but edits to the report.

* [x] Write up background
* [x] Write up variable selection
* [x] Write up Modeling section
* [x] Decide what we put into the discussion
* [x] Organize code

**Comment by dravesb** [comment]
Remaining items include 

- [x] Review discussion section
- [x] Discuss prediction evaluation (MSE compared to what? )
- [x] Decide to include google map vs lasso output? Both? 
- [x] Contributions 
- [x] Appendix I: code for all in-line plots and numbers
